name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
      - name: Clean Gradle Cache
        run: |
          rm -rf ~/.gradle/caches/jars-*
          rm -rf ~/.gradle/caches/modules-*
      - name: Build Plugin (Skip Tests)
        run: ./gradlew clean build -x test
      - name: Verify Plugin Structure
        run: ./gradlew verifyPlugin
