name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Clean Gradle cache
        run: rm -rf ~/.gradle/caches
      - name: Gradle Clean
        run: ./gradlew clean
      - name: Run Tests
        run: ./gradlew test --refresh-dependencies
        env:
          GRADLE_USER_HOME: ${{ github.workspace }}/.gradle
